import '@/app/globals.css'
import type { Metadata } from 'next'
import { type ReactNode } from 'react'

import { Providers } from '@/app/providers'
import WalletNav from '@/components/WalletNav'

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (

    <div className="font-sans antialiased">
      <Providers>
        <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-slate-100">
          <WalletNav />
          {props.children}
        </div>
      </Providers>
    </div>

  )
}
